---
folder: String value
homeworks:
  - folder: String value
    name: String value
    submit_by: String value
    tasks:
      - folder: String value
        name: String value
        language: Any of ['cpp', 'bash']
        ~[optional]~ binary_name: String value
        tests:
          - name: String value
            cmd: String value
            ~[optional]~ output_type: Any of ['string', 'number']
            ~[optional]~ expected_output: Any of ['String value', 'Float value', 'Int value']
            ~[optional]~ timeout: Float value
