---
folder: String value
homeworks:
  - folder: String value
    name: String value
    submit_by: String value
    tasks:
      - folder: String value
        language: Any of ['cpp', 'bash']
        name: String value
        ~[optional]~ binary_name: String value
        ~[optional]~ build_timeout: Float value
        ~[optional]~ compiler_flags: String value
        ~[optional]~ build_type: Any of ['cmake', 'simple']
        ~[optional]~ output_type: Any of ['string', 'number']
        ~[optional]~ tests:
          - name: String value
            ~[optional]~ expected_output: Any of ['String value', 'Float value', 'Int value']
            ~[optional]~ inject_folders:
              - destination: String value
                source: String value
            ~[optional]~ input_args: String value
            ~[optional]~ input_pipe_args: String value
            ~[optional]~ output_pipe_args: String value
            ~[optional]~ run_google_tests: Boolean value
            ~[optional]~ timeout: Float value
