name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install prerequisites
      run: |
        sudo apt install -y libgtest-dev
        python -m pip install --upgrade pip pipenv
    - name: Initialize workspace
      run: >
        pipenv install
    - name: Lint with Black linter
      run: >
        pipenv run black homework_checker --check --diff
    - name: Run unit tests
      run: >
        pipenv run python3 -m unittest discover -v homework_checker/tests/
  report:
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          repository: git@github.com:${{ github.repository }}.wiki.git
      - run: |
          date > generated.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push

