name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install prerequisites
      run: |
        sudo apt install -y libgtest-dev
        python -m pip install --upgrade pip pipenv
    - name: Initialize workspace
      run: >
        pipenv install
    - name: Lint with Black linter
      run: >
        pipenv run black homework_checker
    - name: Run unit tests
      run: >
        pipenv run python3 -m unittest discover -v homework_checker/tests/

