name: CI

on: [push]

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install prerequisites
      run: |
        sudo apt install -y libgtest-dev
        python -m pip install --upgrade pip pipenv black

  lint:
    runs-on: ubuntu-20.04
    needs: setup
    steps:
    - uses: actions/checkout@v2
    - name: Run Black linter
      run: black homework_checker --check --diff

  test:
    runs-on: ubuntu-20.04
    needs: setup

    steps:
    - uses: actions/checkout@v2

    - name: Initialize workspace
      run: >
        pipenv install

    - name: Run unit tests
      run: >
        pipenv run python3 -m unittest discover -v homework_checker/tests/

