name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install prerequisites
      run: python -m pip install --upgrade pip black
    - name: Run Black linter
      run: black homework_checker --check --diff

  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install prerequisites
      run: |
        sudo apt install -y libgtest-dev
        python -m pip install --upgrade pip pipenv
    - name: Initialize workspace
      run: >
        pipenv install
    - name: Run unit tests
      run: >
        pipenv run python3 -m unittest discover -v homework_checker/tests/

