name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable

  test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'

    - name: Install prerequisites
      run: |
        sudo apt install -y libgtest-dev
        python -m pip install --upgrade pip pipenv

    - name: Initialize workspace
      run: >
        pipenv install

    - name: Test
      run: >
        pipenv run python3 -m unittest discover -v homework_checker/tests/

