name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install prerequisites
      run: >
        sudo apt install -y clang++ cmake libgtest-dev

    - name: Initialize workspace
      run: >
        pipenv install

    - name: Test
      run: >
        pipenv run python3 -m unittest discover -v homework_checker/tests/

